# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: better_logs 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "better_logs".freeze
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Kunal Parikh".freeze]
  s.date = "2022-01-27"
  s.description = "Logging for Rails request/response lifecycle in a machine readable format (starting with Splunk)".freeze
  s.email = "kunal@techthumb.in".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".coveralls.yml",
    ".document",
    ".ruby-gemset",
    ".travis.yml",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "better_logs.gemspec",
    "lib/better_logs.rb",
    "lib/better_logs/action_controller.rb",
    "lib/better_logs/action_controller/log_subscriber.rb",
    "lib/better_logs/action_controller/payload.rb",
    "lib/better_logs/action_dispatch.rb",
    "lib/better_logs/action_dispatch/log_subscriber.rb",
    "lib/better_logs/action_dispatch/payload.rb",
    "lib/better_logs/formatters.rb",
    "lib/better_logs/formatters/key_value_formatter.rb",
    "lib/better_logs/initializer.rb",
    "lib/better_logs/railtie.rb",
    "spec/lib/better_logs/action_controller/log_subscriber_spec.rb",
    "spec/lib/better_logs/action_controller/payload_spec.rb",
    "spec/lib/better_logs/action_dispatch/log_subscriber_spec.rb",
    "spec/lib/better_logs/action_dispatch/payload_spec.rb",
    "spec/lib/better_logs/formatters/key_value_formatter_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/techthumb/better_logs".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.6".freeze
  s.summary = "Better logging for Rails request/response lifecycle.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<activesupport>.freeze, ["~> 6.1"])
    s.add_runtime_dependency(%q<actionpack>.freeze, ["~> 6.1"])
    s.add_runtime_dependency(%q<railties>.freeze, ["~> 6.1"])
    s.add_runtime_dependency(%q<flat_keys>.freeze, ["~> 0.0"])
    s.add_runtime_dependency(%q<useragent>.freeze, ["~> 0.10"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 4.1"])
    s.add_development_dependency(%q<bundler>.freeze, ["~> 2.0"])
    s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_development_dependency(%q<rspec>.freeze, ["~> 3.10"])
    s.add_development_dependency(%q<guard-rspec>.freeze, ["~> 4.2"])
    s.add_development_dependency(%q<terminal-notifier-guard>.freeze, ["~> 1.5"])
    s.add_development_dependency(%q<codeclimate-test-reporter>.freeze, ["~> 0.3"])
  else
    s.add_dependency(%q<activesupport>.freeze, ["~> 6.1"])
    s.add_dependency(%q<actionpack>.freeze, ["~> 6.1"])
    s.add_dependency(%q<railties>.freeze, ["~> 6.1"])
    s.add_dependency(%q<flat_keys>.freeze, ["~> 0.0"])
    s.add_dependency(%q<useragent>.freeze, ["~> 0.10"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
    s.add_dependency(%q<bundler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.10"])
    s.add_dependency(%q<guard-rspec>.freeze, ["~> 4.2"])
    s.add_dependency(%q<terminal-notifier-guard>.freeze, ["~> 1.5"])
    s.add_dependency(%q<codeclimate-test-reporter>.freeze, ["~> 0.3"])
  end
end

