# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: better_logs 0.2.3 ruby lib

Gem::Specification.new do |s|
  s.name = "better_logs"
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kunal Parikh"]
  s.date = "2014-09-02"
  s.description = "Logging for Rails request/response lifecycle in a machine readable format (starting with Splunk)"
  s.email = "kunal@techthumb.in"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".coveralls.yml",
    ".document",
    ".ruby-gemset",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "better_logs.gemspec",
    "lib/better_logs.rb",
    "lib/better_logs/action_controller.rb",
    "lib/better_logs/action_controller/log_subscriber.rb",
    "lib/better_logs/action_controller/payload.rb",
    "lib/better_logs/action_dispatch.rb",
    "lib/better_logs/action_dispatch/log_subscriber.rb",
    "lib/better_logs/action_dispatch/payload.rb",
    "lib/better_logs/formatters.rb",
    "lib/better_logs/formatters/key_value_formatter.rb",
    "lib/better_logs/initializer.rb",
    "lib/better_logs/railtie.rb",
    "spec/lib/better_logs/action_controller/log_subscriber_spec.rb",
    "spec/lib/better_logs/action_controller/payload_spec.rb",
    "spec/lib/better_logs/action_dispatch/log_subscriber_spec.rb",
    "spec/lib/better_logs/action_dispatch/payload_spec.rb",
    "spec/lib/better_logs/formatters/key_value_formatter_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/techthumb/better_logs"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.3.0"
  s.summary = "Better logging for Rails request/response lifecycle."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 4.0"])
      s.add_runtime_dependency(%q<actionpack>, ["~> 4.0"])
      s.add_runtime_dependency(%q<railties>, ["~> 4.0"])
      s.add_runtime_dependency(%q<flat_keys>, ["~> 0.0"])
      s.add_runtime_dependency(%q<useragent>, ["~> 0.10"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 4.2"])
      s.add_development_dependency(%q<terminal-notifier-guard>, ["~> 1.5"])
      s.add_development_dependency(%q<codeclimate-test-reporter>, ["~> 0.3"])
    else
      s.add_dependency(%q<activesupport>, ["~> 4.0"])
      s.add_dependency(%q<actionpack>, ["~> 4.0"])
      s.add_dependency(%q<railties>, ["~> 4.0"])
      s.add_dependency(%q<flat_keys>, ["~> 0.0"])
      s.add_dependency(%q<useragent>, ["~> 0.10"])
      s.add_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.14"])
      s.add_dependency(%q<guard-rspec>, ["~> 4.2"])
      s.add_dependency(%q<terminal-notifier-guard>, ["~> 1.5"])
      s.add_dependency(%q<codeclimate-test-reporter>, ["~> 0.3"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 4.0"])
    s.add_dependency(%q<actionpack>, ["~> 4.0"])
    s.add_dependency(%q<railties>, ["~> 4.0"])
    s.add_dependency(%q<flat_keys>, ["~> 0.0"])
    s.add_dependency(%q<useragent>, ["~> 0.10"])
    s.add_dependency(%q<rdoc>, ["~> 4.1"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.14"])
    s.add_dependency(%q<guard-rspec>, ["~> 4.2"])
    s.add_dependency(%q<terminal-notifier-guard>, ["~> 1.5"])
    s.add_dependency(%q<codeclimate-test-reporter>, ["~> 0.3"])
  end
end

